# Generated by Django 4.2.9 on 2025-04-26 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(
                null=True, verbose_name=django.core.validators.MaxValueValidator(100)
            ),
        ),
    ]
