# Generated by Django 4.2.9 on 2025-05-04 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
